apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: view-demo
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: view-demo
    spec:
      #imagePullSecrets:
      #  - name: cubelgrg
      containers:
      - name: view-demo
        image: opencloudregistry.azurecr.io/clouddemo/view-demo:latest
        ports:
        - containerPort: 8080
        name : view-demo